// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateSnapshot(arg1:string):Promise<main.SnapshotResponse>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function ExportConfig(arg1:string):Promise<string>;

export function GetBaselinePath():Promise<string>;

export function GetCurrentConfig():Promise<main.ConfigResponse>;

export function GetLastReportPath():Promise<string>;

export function GetLastScan():Promise<main.ScanResult>;

export function ListSnapshots():Promise<Array<main.SnapshotResponse>>;

export function LoadBaseline():Promise<main.BaselineResp>;

export function LoadSnapshot(arg1:string):Promise<main.ConfigResponse>;

export function ReloadConfig():Promise<main.ConfigResponse>;

export function RunScan():Promise<main.ScanResult>;

export function SaveConfig(arg1:main.ConfigFormData):Promise<void>;

export function SaveCurrentConfigPath():Promise<string>;
