// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSnapshot(arg1) {
  return window['go']['main']['App']['CreateSnapshot'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetBaselinePath() {
  return window['go']['main']['App']['GetBaselinePath']();
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetLastReportPath() {
  return window['go']['main']['App']['GetLastReportPath']();
}

export function GetLastScan() {
  return window['go']['main']['App']['GetLastScan']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function LoadBaseline() {
  return window['go']['main']['App']['LoadBaseline']();
}

export function LoadSnapshot(arg1) {
  return window['go']['main']['App']['LoadSnapshot'](arg1);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RunScan() {
  return window['go']['main']['App']['RunScan']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCurrentConfigPath() {
  return window['go']['main']['App']['SaveCurrentConfigPath']();
}
